name: graphics-debug-tools-bboozzoo
version: "1.0"
summary: collection of utilities for debugging graphics issues
description: |
  A collection of utilities for debugging graphics/compute issues. Those are:
    - glxinfo
    - xrandr
    - vulkaninfo
    - eglinfo
    - clinfo
confinement: strict
base: core18
architectures:
  - amd64

layout:
  # NOTE: this does not work yet, we found a bug in snap-update-ns
  #
  # OpenCL ICD loader needs to see vendor icd files in a very specific place
  # /etc/OpenCL/vendors/mesa.icd:
  #   bind-file: $SNAP/etc/OpenCL/vendors/mesa.icd
  # use beignet ICD provided by the snap
  # /etc/OpenCL/vendors/intel-beignet-x86_64-linux-gnu.icd:
  #   bind-file: $SNAP/intel-beignet-x84_64-linux-gnu-icd
  # Vulkan ICD loader needs to see vendor icd files in a very specific place
  /usr/share/vulkan:
    bind: $SNAP/usr/share/vulkan

hooks:
  # hooks collects OpenCL ICD files
  connect-plug-opengl:
    plugs:
      - opengl

apps:
  glxinfo:
    command: usr/bin/glxinfo
    plugs:
      - x11
      - opengl

  xrandr:
    command: usr/bin/xrandr
    plugs:
      - x11
      - opengl

  vulkaninfo:
    command: usr/bin/vulkaninfo
    plugs:
      - x11
      - opengl

  eglinfo:
    command: bin/eglvendor-wrapper $SNAP/usr/bin/eglinfo
    plugs:
      - x11
      - opengl

  clinfo:
    command: usr/bin/clinfo
    plugs:
      - x11
      - opengl
    environment:
      OCL_ICD_VENDORS: $SNAP_COMMON/OpenCL/vendors

parts:
  glxinfo:
    plugin: nil
    stage-packages:
      - mesa-utils

  xrandr:
    plugin: nil
    stage-packages:
      - x11-xserver-utils

  vulkaninfo:
    plugin: nil
    stage-packages:
      - vulkan-utils

  mesa-vulkan:
    plugin: nil
    stage-packages:
      - mesa-vulkan-drivers

  clinfo:
    plugin: nil
    stage-packages:
      - clinfo
      - mesa-opencl-icd

  beignet:
    plugin: nil
    stage-packages:
      - beignet-opencl-icd

  beignet-override:
    plugin: nil
    override-build: |
      # beignet ICD file hardcodes the path to libcl.so under
      # /usr/lib/x86_64-linux-gnu/beignet, generate a new icd file pointing to
      # $SNAP specific location that we will drop in the right place
      echo /snap/graphics-debug-tools-bboozzoo/current/usr/lib/x86_64-linux-gnu/beignet/libcl.so > $SNAPCRAFT_PART_INSTALL/intel-beignet-x86_64-linux-gnu.icd
    after:
      - beignet
    stage:
      - intel-beignet-x86_64-linux-gnu.icd

  eglinfo:
    plugin: waf
    source: https://github.com/dv1/eglinfo
    source-type: git
    configflags:
      - --platform=x11
      - --prefix=/usr
      - --verbose
    build-packages:
      - gcc
      - g++
      - libx11-dev
      - libegl1-mesa-dev
      - libgl1-mesa-dev
    stage:
      - usr/bin/eglinfo

  eglvendor-wrapper:
    plugin: nil
    override-build: |
      set -ex
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cat <<\EOF > $SNAPCRAFT_PART_INSTALL/bin/eglvendor-wrapper
      #!/bin/sh
      if [ -d /var/lib/snapd/lib/glvnd/egl_vendor.d ]; then
          __EGL_VENDOR_LIBRARY_DIRS=/var/lib/snapd/lib/glvnd/egl_vendor.d
          export __EGL_VENDOR_LIBRARY_DIRS
      fi
      exec "$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/eglvendor-wrapper
    stage:
      - bin/eglvendor-wrapper
