name: graphics-debug-tools-bboozzoo
version: 1.0
summary: collection of utilities for debugging graphics issues
description: |
  A collection of utilities for debugging graphics issues. Those are:
    - glxinfo
    - xrandr
    - vulkaninfo
    - eglinfo

apps:
  glxinfo:
    command: usr/bin/glxinfo
    plugs:
      - x11
      - opengl

  xrandr:
    command: usr/bin/xrandr
    plugs:
      - x11
      - opengl

  vulkaninfo:
    command: usr/bin/vulkaninfo
    plugs:
      - x11
      - opengl

  eglinfo:
    command: bin/eglvendor-wrapper $SNAP/usr/bin/eglinfo
    plugs:
      - x11
      - opengl

parts:
  glxinfo:
    plugin: nil
    stage-packages:
      - mesa-utils

  xrandr:
    plugin: nil
    stage-packages:
      - x11-xserver-utils

  vulkaninfo:
    plugin: nil
    stage-packages:
      - vulkan-utils

  eglinfo:
    plugin: waf
    source: https://github.com/dv1/eglinfo
    source-type: git
    configflags:
      - --platform=x11
      - --prefix=/usr
      - --verbose
    build-packages:
      - gcc
      - g++
      - libx11-dev
      - libegl1-mesa-dev
      - libgl1-mesa-dev
    stage:
      - usr/bin/eglinfo

  eglvendor-wrapper:
    plugin: nil
    install: |
      set -ex
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cat <<\EOF > $SNAPCRAFT_PART_INSTALL/bin/eglvendor-wrapper
      #!/bin/sh
      if [ -d /var/lib/snapd/lib/glvnd/egl_vendor.d ]; then
          __EGL_VENDOR_LIBRARY_DIRS=/var/lib/snapd/lib/glvnd/egl_vendor.d
          export __EGL_VENDOR_LIBRARY_DIRS
      fi
      exec "$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/eglvendor-wrapper
    stage:
      - bin/eglvendor-wrapper
