name: graphics-debug-tools-bboozzoo
version: 1.0
summary: collection of utilities for debugging graphics issues
description: |
  A collection of utilities for debugging graphics issues. Those are:
    - glxinfo
    - xrandr

apps:
  glxinfo:
    command: usr/bin/glxinfo
    plugs:
      - x11
      - opengl

  xrandr:
    command: usr/bin/xrandr
    plugs:
      - x11
      - opengl

parts:
  glxinfo:
    plugin: nil
    stage-packages:
      - mesa-utils

  xrandr:
    plugin: nil
    stage-packages:
      - x11-xserver-utils
